version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  test:
    image: positron-critical-arm:latest
    build:
      context: .
      dockerfile: Dockerfile.critical.arm
      args:
        TOKEN: ${GITHUB_TOKEN}
    container_name: test
    ports:
      - "8080:8080"
      - "5900:5900"
      - "9323:9323"
    networks:
      - mynetwork
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb
    volumes:
      - ./pdol_rsa:/usr/src/positron-license/pdol/target/debug/pdol_rsa
    command: >
      bash -c "chmod 600 /usr/src/positron-license/pdol/target/debug/pdol_rsa && /home/runner/startup.sh"

volumes:
  postgres-data:
